version: "3"
services:
  tavernai:
    build: ..
    container_name: tavernai
    image: tavernai/tavernai:latest
    network_mode: "container:gluetun"
    #ports:
     # - "8000:8000"
    volumes:
      - "./config:/home/node/app/config"
    restart: unless-stopped